### ISSUE TITLE
Check to see whether End Date is after Start Date

### ISSUE THREAD

**Issue by aj019** [openMF/self-service-app#236] opened 2017-03-23 06:02 UTC
**Summary:**

In Transactions while selecting start date and end date there is no check to see whether end date is after start date.

**Steps to reproduce:**

1) Open the app
2) Go To savings
3) Go To saving details
4) Go To saving transactions
5) Enter start date as 23 March and end date as 21 March

**Expected behavior:**

There should be a toast to let the user know that the end date is before the start date

**Observed behavior:**

The filter produces no result on entering wrong dates

**Device and Android version:**

Nexus 5 API 23

**Screenshots:**

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/7893859/24234057/5447bd56-0fbc-11e7-9155-302e1fc14fdd.gif)

**Comment by aj019** [comment] 2017-03-23 06:03
I would like to work on this issue.

**Comment by ashish05182001** [comment] 2017-03-29 14:32
Hello @aj019 , @edcable 
I have sent an PR for this bug. Please review it.
Thanks

**Screenshots:**
![whatsapp image 2017-03-29 at 7 33 31 pm](https://cloud.githubusercontent.com/assets/13850995/24478780/cb0d661a-14f9-11e7-883c-fa42785a31c9.jpeg)
![whatsapp image 2017-03-29 at 7 33 37 pm](https://cloud.githubusercontent.com/assets/13850995/24478773/c4f263de-14f9-11e7-874f-87cde844e61a.jpeg)

![whatsapp image 2017-03-29 at 7 33 34 pm](https://cloud.githubusercontent.com/assets/13850995/24478779/c8ef8dc2-14f9-11e7-98c8-4e6f65e7283c.jpeg)

**Comment by dilpreet2028** [comment] 2017-06-15 05:24
@therajanmaurya Duplicate of issue #167

**Closed as completed** 2017-07-27 09:10 UTC
Labels: duplicate
