### ISSUE TITLE
No option available to edit user's profile information

### ISSUE THREAD

**Issue by shaljais01** [openMF/self-service-app#1275] opened 2020-01-19 08:19 UTC
Summary:

User cannot edit User Details in User Details fragment. 

Steps to reproduce:

Open App -> Click on the profile pic -> No option to change user details

Expected behaviour:

The user should be able to change his information by clicking on a Edit profile button

Observed behaviour:

No such Edit Profile button is available

Device and Android version:

Android 6.0
Motorola E3 Power

**Comment by shaljais01** [comment] 2020-01-19 08:20
I would like to work on this issue, May I?

**Comment by divyank00** [comment] 2020-01-19 11:55
Can i work on this?

**Comment by miPlodder** [comment] 2020-11-16 18:47
Duplicate of https://github.com/openMF/mifos-mobile/issues/1293

**Closed as completed by miPlodder** 2020-11-16 18:47 UTC
