### ISSUE TITLE
Navigation View Margin Error

### ISSUE THREAD

**Issue by YashishDua** [openMF/self-service-app#708] opened 2018-03-04 08:45 UTC
**Summary:**

On scrolling down navigation view has an unnecessary margin over top

**Steps to reproduce:**

Reducing the margin relatively

**Expected behaviour:**

No margin at top ( White Color must not be there)

**Observed behaviour:**

When Navigation view scrolled down, there is a margin at top revealing white color over blue. It's not syncing with UI

**Comment by mohak1712** [comment] 2018-03-04 09:42
@YashishDua can you add a screenshot and I think this is similar to #692

**Comment by therajanmaurya** [comment] 2018-06-07 05:55
Duplicate of #692

**Closed as completed by therajanmaurya** 2018-06-07 05:55 UTC
