### ISSUE TITLE
Unfortunately, Mifos Mobile has stopped

### ISSUE THREAD

**Issue by stanfidu** [openMF/self-service-app#1109] opened 2019-03-14 20:29 UTC
**Summary:**

Unfortunately, Mifos Mobile has stopped.
Already try to disable instant run

**Steps to reproduce:**

Install app on Android Phone with android version 4.4.3
Launch the app

**Expected behaviour:**

Launch successfully

**Observed behaviour:**

App close and phone displays "Unfortunately, Mifos Mobile has stopped"

**Device and Android version:**
Model Number: HUAWEI Y536A1
RAM: 1GB
Resolution: 480 * 854
Android Version: 4.4.3

**Comment by RajaVamsi11** [comment] 2019-03-15 07:14
@stanfidu Can you please attach GIF.

**Comment by stanfidu** [comment] 2019-03-18 18:45
@RajaVamsi11 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48560205/54555094-675e6780-498c-11e9-91fa-9fabc49707a3.gif)

**Comment by RajaVamsi11** [comment] 2019-03-18 20:59
@stanfidu seems like a valid issue.

**Comment by stanfidu** [comment] 2019-03-19 14:18
@RajaVamsi11 how to fix it?

**Comment by RajaVamsi11** [comment] 2019-03-19 14:37
@stanfidu The errors will be shown in logcat of the Android studio when you run the device. Follow the logcat, you will find out where the app was failing.

**Comment by stanfidu** [comment] 2019-03-26 20:12
@RajaVamsi11 

03-26 16:08:52.457 13713-13713/org.mifos.mobilebanking E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mifos.mobilebanking, PID: 13713
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/org.mifos.mobilebanking-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.mifos.mobilebanking-1, /vendor/lib, /data/cust/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5023)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4612)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4552)
        at android.app.ActivityThread.access$1800(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5272)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/org.mifos.mobilebanking-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.mifos.mobilebanking-1, /vendor/lib, /data/cust/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5008)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4612) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4552) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5272) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by prashantkh19** [comment] 2019-04-09 20:06
Duplicate of #886 
@stanfidu Seems like a dex merge problem. Try configuring the multidex for your API level.

**Comment by prashantkh19** [comment] 2019-04-10 08:06
@stanfidu Refer #1164

**Comment by stanfidu** [comment] 2019-04-10 13:23
Thanks @prashantkh19 i will try to apply fixes

**Closed as completed** 2023-10-14 07:21 UTC
