### ISSUE TITLE
No scrollview in AboutUs Fragment

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1402] opened 2020-03-09 18:24 UTC
**Summary:**

AboutUs Fragment does not have the `NestedScrollView` and hence it can create problems like not showing complete user interface in certain devices or in landscape mode for other devices

**Steps to reproduce:**

* Go to AboutUs Fragment from Navigation drawer
* Try reproducing the issue with landscape mode (if possible with your device)

**Expected behaviour:**

It is safe to add ScrollView so that our app becomes robust enough to handle various screen sizes and landscape orientation

**Observed behaviour:**

In certain devices complete user interface might not be visible on screen

**Device and Android version:**

Xiaomi PocoF1
Android 9
Stock rom

**Comment by ShivangiSingh17** [comment] 2020-03-12 06:23
Refer to this issue: https://github.com/openMF/mifos-mobile/issues/1024
I think the issue you opened is already into action and doesn't need to be referred again.

**Comment by devansh-299** [comment] 2020-03-12 09:31
@ShivangiSingh17 should I close this issue and related PR? because for Portrait mode we don't need scrollview for this fragment

**Comment by ShivangiSingh17** [comment] 2020-03-12 14:14
@devansh-299 It's better if you close it because the issue is already under process and creating PR multiple times for the same issue (though different ragments)creates duplication.

**Closed as completed** 2020-03-12 14:56 UTC
