### ISSUE TITLE
In Third party Transfer Activity, User can continue with the transfer even if no item is selected in Pay From spinner

### ISSUE THREAD

**Issue by vibhusharma101** [openMF/self-service-app#1279] opened 2020-01-19 11:18 UTC
**Summary:**

In Third party Transfer Activity, User can continue with the transfer even if no item is selected in Pay From spinner. If the user has not selected any account user should not be able to go to the next step.

Here a toast message should appear telling the user that no account has been selected.

**Device and Android version:**
Device Oppo Rmx1811

![C2F0A24F-C5B5-46A7-9A15-990B72B60CC5](https://user-images.githubusercontent.com/39101226/72680061-7269b300-3adb-11ea-9f5d-06e5e830c9fc.JPG)

@geekanamika  can I work on this?

**Comment by shaljais01** [comment] 2020-01-19 11:41
vibhusharma101 Can I work on this issue?

**Comment by shaljais01** [comment] 2020-01-19 11:42
@vibhusharma101 Can I work on this issue?

**Comment by vibhusharma101** [comment] 2020-01-19 11:44
@shaljais01 I am working on this, I am waiting from confirmation from maintainers

**Comment by divyank00** [comment] 2020-01-19 11:46
I have already solved this in issue #1272

**Comment by vibhusharma101** [comment] 2020-01-19 12:03
okay

**Comment by devansh-299** [comment] 2020-01-20 13:37
@vibhusharma101 its duplicate of #1272 , you can close this issue

**Closed as completed** 2020-01-20 14:34 UTC
