### ISSUE TITLE
Unable to login after updating api endpoint

### ISSUE THREAD

**Issue by HilaryKinyua** [openMF/self-service-app#1378] opened 2020-02-25 11:49 UTC
Someone to clearly explain how we should change the endpoints because after updating the endpoints the app is not logging in.
I even went ahead to change the following codes to our endpoints:
              public static final String API_ENDPOINT = "mobile.openmf.org";
              public static final String API_PATH = "/fineract-provider/api/v1/self/";
              public static final String PROTOCOL_HTTPS = "https://";

Still not working.Someone to help me here it's urgent

**Comment by iamsharad98** [comment] 2020-02-26 11:31
You can ask about this issue in OpenMF- Gitter [https://gitter.im/openMF/mifos](channel ) .

**Comment by refactor-droidyy** [comment] 2020-03-02 19:58
@anonghostteamz same here cannot login whats the correct api endpoints.

**Comment by brandhuge** [comment] 2020-10-14 14:45
@anonghostteamz @HilaryKinyua Do you get solaution to the login problem. Please share I am having similar issue.

Thanks

**Comment by luckyman20** [comment] 2023-06-04 02:43
Duplicate of #1380

**Closed as completed by luckyman20** 2023-06-04 02:43 UTC
