### ISSUE TITLE
Blank user profile is visible without internet

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1062] opened 2019-02-20 20:19 UTC
**Summary:**

When we have no internet, a blank user profile is visible for a moment, and then we see not available page.

**Steps to reproduce:**
No internet -> User profile
**Expected behaviour:**

Show only one page

(Maybe we need to display the page only after loading, otherwise it leads to a bad user experience)
![videotogif_2019 02 20_22 41 20](https://user-images.githubusercontent.com/38163725/53121740-e2458580-357a-11e9-9b20-ac08379d577b.gif)

**Comment by devansh-299** [comment] 2019-08-20 05:21
I tried but  I couldn't reproduce the same issue

**Comment by geekanamika** [comment] 2019-10-13 12:21
@shiv07tiwari This issue doesn't exists anymore, checked on emulator & motorola physical device. We can close this issue, if it still persists, please reopen with steps to reproduce it.

**Closed as completed by geekanamika** 2019-10-13 12:21 UTC
